name: build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          check-latest: true 

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: modern-rpc-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            modern-rpc

      - name: Test
        run: mvn verify
